# UAE country-specific configuration  
# Taxes, legal requirements and regulatory framework

country:
  name: "United Arab Emirates"
  code: "UAE" 
  currency: "AED"  # UAE Dirhams
  language: "ar"

# Tax and regulatory framework
taxes:
  transfer_tax_rate: 0.04             # 4% Dubai Land Department transfer fee
  registration_fees: 0.002            # 0.2% registration fees
  trustee_fees: 0.0025               # 0.25% trustee fees
  mortgage_registration: 0.0025      # 0.25% mortgage registration
  
  # Development taxes and fees
  municipality_fees_rate: 0.02       # 2% municipality development fees
  housing_fee_annual: 0.05           # 5% annual housing fee on rental income
  
  # VAT (no income tax for most emirates)
  vat_rate: 0.05                     # 5% VAT on goods and services
  corporate_tax_rate: 0.09           # 9% corporate tax (introduced 2023)
  withholding_tax_rate: 0.00         # No withholding tax

# Legal and regulatory requirements
legal:
  foreign_ownership:
    allowed: true
    restrictions: "100% foreign ownership in designated areas"
    max_ownership_pct: 1.00          # 100% in freehold areas
    freehold_areas: ["Dubai", "Abu Dhabi", "Ras Al Khaimah", "Ajman"]
    
  permits:
    building_permit_required: true
    environmental_clearance: true
    fire_safety_approval: true
    utility_connections_required: true
    dewa_connection_required: true   # Dubai Electricity & Water Authority
    
  timelines:
    permit_processing_days: 30       # Faster processing in UAE
    title_transfer_days: 7           # Quick title transfer
    construction_approval_days: 21   # Construction plan approval

# Banking and financing
financing:
  max_ltv_ratio: 0.75               # 75% max LTV for residents, 60% for non-residents
  typical_interest_rate: 0.045      # 4.5% typical interest rate
  loan_origination_fee: 0.01        # 1% loan origination fee
  min_equity_requirement: 0.25      # 25% minimum equity for development
  
  # Specific to non-residents
  non_resident_max_ltv: 0.60        # 60% max LTV for non-residents
  non_resident_income_multiplier: 7  # 7x income multiplier limit

# Compliance requirements
compliance:
  anti_money_laundering: true
  beneficial_ownership_disclosure: true
  environmental_impact_assessment: true
  seismic_building_standards: false  # Not seismically active
  escrow_account_mandatory: true     # Mandatory escrow for off-plan sales
  rera_registration: true            # Real Estate Regulatory Agency registration