# Global defaults for TerraFlow system
# Units and system-wide configuration

units:
  area: "sqm"  # square meters
  currency: "USD"  # US Dollars (default)
  distance: "m"  # meters
  
# Default scoring weights and thresholds
scoring:
  weights:
    residual_score: 0.40    # Weight for residual land value assessment
    land_pct_score: 0.35    # Weight for land % of GDV assessment  
    breakeven_score: 0.25   # Weight for breakeven analysis
    
  thresholds:
    residual_margin_buffer: 0.10      # 10% buffer for healthy residual
    land_gdv_normal_min: 0.15         # 15% minimum normal land % of GDV
    land_gdv_normal_max: 0.25         # 25% maximum normal land % of GDV  
    land_gdv_warning_max: 0.30        # 30% warning threshold
    breakeven_buffer_good: 0.80       # 80% breakeven vs market for good score
    breakeven_buffer_warning: 0.85    # 85% breakeven vs market for warning

# Development standards
development:
  efficiency_ratio:
    min: 0.60    # 60% minimum efficiency ratio
    max: 0.95    # 95% maximum efficiency ratio
    
  profit_target:
    min: 0.05    # 5% minimum profit target
    max: 0.50    # 50% maximum profit target
    
  far_limits:
    min: 0.1     # Minimum Floor Area Ratio
    max: 10.0    # Maximum Floor Area Ratio
    
  holding_period:
    min_months: 1      # Minimum holding period
    max_months: 120    # Maximum holding period (10 years)

# Default validation rules
validation:
  strict_mode: false        # Enable strict validation
  warn_on_extremes: true    # Show warnings for extreme values
  auto_correct: false       # Auto-correct invalid inputs