# Jordan country-specific configuration
# Taxes, legal requirements and regulatory framework

country:
  name: "Jordan"
  code: "JO"
  currency: "JOD"  # Jordanian Dinar
  language: "ar"

# Tax and regulatory framework
taxes:
  transfer_tax_rate: 0.075        # 7.5% transfer tax on property transactions
  stamp_duty_rate: 0.005          # 0.5% stamp duty
  registration_fees: 0.002        # 0.2% registration fees
  legal_fees_rate: 0.01           # 1% typical legal fees
  
  # Development taxes
  municipal_fees_rate: 0.03       # 3% municipal development fees
  infrastructure_levy: 0.02       # 2% infrastructure contribution
  
  # VAT and income taxes
  vat_rate: 0.16                  # 16% VAT on services and materials
  corporate_tax_rate: 0.20        # 20% corporate income tax
  withholding_tax_rate: 0.05      # 5% withholding tax on foreign investors

# Legal and regulatory requirements
legal:
  foreign_ownership:
    allowed: true
    restrictions: "Foreign investors can own property with registration"
    max_ownership_pct: 1.00       # 100% foreign ownership allowed
    
  permits:
    building_permit_required: true
    environmental_clearance: true
    fire_safety_approval: true
    utility_connections_required: true
    
  timelines:
    permit_processing_days: 60    # Typical building permit processing time
    title_transfer_days: 30       # Property title transfer time
    construction_approval_days: 45 # Construction plan approval

# Banking and financing
financing:
  max_ltv_ratio: 0.80            # 80% maximum loan-to-value
  typical_interest_rate: 0.065   # 6.5% typical interest rate
  loan_origination_fee: 0.01     # 1% loan origination fee
  min_equity_requirement: 0.25   # 25% minimum equity for development

# Compliance requirements  
compliance:
  anti_money_laundering: true
  beneficial_ownership_disclosure: true
  environmental_impact_assessment: true
  seismic_building_standards: true