# Jordan financial parameters and development economics
# Market-specific profit targets and cost benchmarks

finance:
  # Profit target ranges by development type
  profit_targets:
    residential_low_risk: 0.15      # 15% for established areas
    residential_medium_risk: 0.20   # 20% for developing areas
    residential_high_risk: 0.25     # 25% for emerging areas
    commercial_retail: 0.18         # 18% for retail developments
    commercial_office: 0.16         # 16% for office developments
    mixed_use: 0.22                 # 22% for mixed-use projects
    
  # Soft cost benchmarks as percentage of hard costs
  soft_costs:
    architectural_design: 0.06      # 6% for architectural services
    engineering: 0.04               # 4% for structural/MEP engineering
    permits_approvals: 0.02         # 2% for permits and approvals
    legal_fees: 0.015               # 1.5% for legal services
    marketing_sales: 0.025          # 2.5% for marketing and sales
    financing_costs: 0.03           # 3% for construction financing
    project_management: 0.02        # 2% for project management
    contingency: 0.05               # 5% contingency
    total_soft_cost_pct: 0.16       # 16% total soft costs
    
  # Construction financing parameters
  construction_finance:
    typical_interest_rate: 0.08     # 8% construction loan rate
    loan_to_cost_ratio: 0.75        # 75% loan-to-cost
    interest_reserve_months: 18     # 18 months interest reserve
    origination_fee: 0.015          # 1.5% origination fee
    
  # Sales and marketing assumptions
  sales:
    absorption_rate_units_month: 3.5  # 3.5 units per month absorption
    presale_requirement_pct: 0.30     # 30% presales required
    sales_commission_rate: 0.03       # 3% sales commission
    price_escalation_annual: 0.04     # 4% annual price appreciation
    
  # Development timeline assumptions
  timeline:
    planning_design_months: 6       # 6 months for planning and design
    permitting_months: 4            # 4 months for permits
    construction_months: 18         # 18 months construction
    sales_marketing_months: 12      # 12 months sales and marketing
    total_project_months: 24        # 24 months total project timeline

# Risk factors and adjustments  
risk_factors:
  market_volatility_adjustment: 0.02   # 2% additional margin for volatility
  regulatory_risk_premium: 0.015       # 1.5% for regulatory changes
  currency_risk_adjustment: 0.01       # 1% for currency fluctuation
  liquidity_discount: 0.03             # 3% discount for illiquid markets
  
# Benchmarking standards
benchmarks:
  land_cost_gdv_typical: 0.20          # 20% land cost as % of GDV
  land_cost_gdv_maximum: 0.28          # 28% maximum acceptable
  debt_service_coverage_min: 1.25      # Minimum 1.25x DSCR
  return_on_equity_target: 0.18        # 18% target ROE