# Jordan market data configuration
# Keys and structure for market research data lookup

market:
  # Market data sources and keys
  data_sources:
    primary: "jordan_market_research"
    fallback: "regional_mena_data"
    update_frequency: "quarterly"
    
  # Geographic market segments
  locations:
    amman_west:
      name: "Amman West"
      tier: 1
      demand_score: 5
      liquidity_score: 4
    amman_central:
      name: "Amman Central" 
      tier: 1
      demand_score: 4
      liquidity_score: 5
    amman_east:
      name: "Amman East"
      tier: 2  
      demand_score: 3
      liquidity_score: 3
    zarqa:
      name: "Zarqa"
      tier: 2
      demand_score: 3
      liquidity_score: 2
    irbid:
      name: "Irbid"
      tier: 2
      demand_score: 3
      liquidity_score: 2
    aqaba:
      name: "Aqaba"
      tier: 2
      demand_score: 4
      liquidity_score: 3

  # Data categories and keys for lookup
  data_keys:
    # Land pricing  
    land_comps:
      - "land_comp_min"
      - "land_comp_avg" 
      - "land_comp_max"
      - "land_per_buildable_avg"
      
    # Sale pricing
    sale_prices:
      - "sale_price_min_jod_sqm"
      - "sale_price_avg_jod_sqm"
      - "sale_price_max_jod_sqm" 
      - "price_per_buildable_jod"
      
    # Construction costs
    construction_costs:
      - "construction_cost_min_jod"
      - "construction_cost_avg_jod"
      - "construction_cost_max_jod"
      - "soft_cost_pct_typical"
      
    # Market indicators
    market_indicators:
      - "absorption_rate_units_month"
      - "land_gdv_benchmark_pct"
      - "profit_margin_benchmark_pct"
      - "demand_score"
      - "liquidity_score"
      - "volatility_score"
      - "last_updated"

  # Validation thresholds for market data
  validation:
    land_price_variance_threshold: 0.50    # 50% variance warning
    sale_price_variance_threshold: 0.30    # 30% variance warning
    cost_escalation_annual_max: 0.15       # 15% maximum annual cost increase
    data_freshness_months: 6               # Data older than 6 months flagged
    
  # Default values when market data unavailable
  fallback_values:
    land_comp_avg_jod_sqm: 85              # 85 JOD per sqm default
    sale_price_avg_jod_sqm: 420            # 420 JOD per sqm default
    construction_cost_avg_jod_sqm: 190     # 190 JOD per sqm default
    absorption_rate: 3.0                   # 3 units per month
    profit_margin_benchmark: 0.20          # 20% profit margin

# Market research integration settings
integration:
  api_endpoints:
    market_data_service: "https://api.jordan-realestate.gov.jo/v1/market"
    comparable_sales: "https://api.jordan-realestate.gov.jo/v1/comps"
    
  refresh_schedule:
    automatic_refresh: true
    refresh_interval_hours: 24
    weekend_refresh: false
    
  data_quality:
    min_comparable_count: 5               # Minimum 5 comparables required
    max_data_age_days: 180               # Maximum 180 days old
    confidence_threshold: 0.80           # 80% confidence requirement