# Jordan zoning classifications and development parameters
# Based on Jordanian building codes and municipal regulations

zoning:
  # Residential zones
  R1:
    name: "Low Density Residential"
    far_max: 1.2
    coverage_max: 0.40
    height_max_m: 12
    floors_max: 3
    setback_front_m: 5
    setback_side_m: 3
    setback_rear_m: 4
    parking_ratio: 1.5  # spaces per unit
    
  R2:
    name: "Medium Density Residential"  
    far_max: 2.0
    coverage_max: 0.50
    height_max_m: 20
    floors_max: 5
    setback_front_m: 4
    setback_side_m: 2
    setback_rear_m: 3
    parking_ratio: 1.2
    
  R3:
    name: "High Density Residential"
    far_max: 3.0
    coverage_max: 0.60
    height_max_m: 35
    floors_max: 10
    setback_front_m: 6
    setback_side_m: 3
    setback_rear_m: 5
    parking_ratio: 1.0
    
  # Commercial zones
  C1:
    name: "Local Commercial"
    far_max: 2.5
    coverage_max: 0.70
    height_max_m: 25
    floors_max: 6
    setback_front_m: 3
    setback_side_m: 2
    setback_rear_m: 3
    parking_ratio: 3.0  # spaces per 100 sqm
    
  C2:
    name: "General Commercial"
    far_max: 4.0
    coverage_max: 0.75
    height_max_m: 40
    floors_max: 12
    setback_front_m: 4
    setback_side_m: 3
    setback_rear_m: 4
    parking_ratio: 2.5
    
  # Mixed use zones  
  MU1:
    name: "Mixed Use Low Rise"
    far_max: 2.5
    coverage_max: 0.55
    height_max_m: 25
    floors_max: 7
    setback_front_m: 4
    setback_side_m: 2
    setback_rear_m: 3
    parking_ratio: 1.5
    residential_component_min: 0.30
    
  MU2:
    name: "Mixed Use High Rise"
    far_max: 5.0
    coverage_max: 0.65
    height_max_m: 60
    floors_max: 18
    setback_front_m: 6
    setback_side_m: 4
    setback_rear_m: 6
    parking_ratio: 1.2
    residential_component_min: 0.20

# Special requirements and design standards
design_standards:
  efficiency_ratios:
    residential: 0.82      # Typical efficiency for residential
    commercial: 0.88       # Typical efficiency for commercial
    mixed_use: 0.85        # Typical efficiency for mixed use
    
  accessibility:
    elevator_required_floors: 4    # Buildings over 3 floors need elevators
    disabled_access_required: true
    fire_stairs_required_floors: 3
    
  environmental:
    green_building_incentives: true
    solar_orientation_requirements: true
    water_conservation_mandatory: true
    insulation_standards: "ASHRAE 90.1"